- name: variables
  hosts: localhost
  connection: local
  vars:
    # Play level variables, global variables
    COURSE: Devops
    DURATION: 120 hr
    TRAINER: Trinath Reddy
  tasks:
  - name: Print the variables
    vars: # Task level variables
    Local variables
      NAME: Trinath Reddy
    ansible.builtin.debug:
      msg: "My name is {{COURSE}}, i am working as a {{DURATION}}, working location is  {{TRAINER}}"

  - name: Print the variables1
    ansible.builtin.debug:
      msg: "My name is {{COURSE}}, i am working as a {{DURATION}}, working location is  {{TRAINER}}"
