- name: filters
  hosts: localhost
  connection: local
  tasks:
  - name: handle undefined variables
    ansible.builtin.debug:
      msg: "Hello {{ person | default('Trinath') }}"

  - name: convet string to list
    vars:
      fruits: "apple, banana, orange" # string 
    ansible.builtin.denug:
      msg: "fruits are: {{ fruits | split (',') }}"
