- name: filters
  hosts: localhost
  connection: local
  tasks:
  - name: handle undefined variables
    ansible.builtin.debug:
      msg: "Hello {{ person | default('Trinath') }}"

  - name: convet string to list
    vars:
      fruits: "apple, banana, orange" # string 
    ansible.builtin.debug:
      msg: "fruits are: {{ fruits | split (',') }}"

  - name: convert map into list
    vars:
      course:
        name: devops
        duration: "120 hr"
        trainer: trinath
    ansible.builtin.debug:
      msg: "course: {{ course | dict2items }}"

  - name: convert list to map
    vars:
      course:
      - { 'key': 'name', 'value': 'devops' }
      - { 'key': 'duration', 'value': '120 hr' }
      - { 'key': 'trainer', 'value': 'trinath' }
    ansible.builtin.debug:
      msg: "course: {{ course | items2dict }}"

  - name: convert upper to lower
    vars:
      name: Trinath Reddy
    ansible.builtin.debug:
      msg: "Hello {{ name | lower }}"

  - name: convert lower to upper
    vars:
      name: trinath reddy
    ansible.builtin.debug:
      msg: "Hello {{ name | upper }}"

  - name: print min and max numbers
    vars: 
      numbers: [1,14,20,30,55,57,98]
    ansible.builtin.debug:
      msg: "Min is: {{ numbers | min }}, Max is: {{ numbers | max }}"

  - name: check ipaddress is valid or not 
     vars: 
       ipaddr: "2559.255.255.255"
    ansible.builtin.debug: 
      msg: "{{ ip | ansible.utils.ipaddr }}"
