- name: create EC2 instance and r53 records
  hosts: localhost
  connection: local
  vars:
    subnet_id: subnet-0452ce0b87e65b4ee
    ami_id: ami-09c813fb71547fc4f
    sg_id: sg-0e142280b2978f20a
    instance_type: t2.micro
    instances:
    - mysql
    - backend
    - frontend
  tasks:
  - name: create ec2 instances
    amazon.aws.ec2_instance:
      name: "{{ item }}"
      subnet_id: "{{ subnet_id }}"
      image_id: "{{ ami_id }}"
      instance_type: "{{ instance_type }}"
      security_group: "{ sg_id }"
    loop: "{{ instances }}"
