- name: crate ec2 and route53 records
  hosts: localhost
  connection: local
  vars:
    subnet_id: subnet-0074fad9a325101aa
    sg_id: sg-0d7e203e4f0120287
    ami_id: ami-09c813fb71547fc4f
    instance_type: t2.micro
    zone: trinath.online
    instances:
    - mysql
    - backend
    - frontend
  tasks:

  - name: install python libraries
    ansible.builtin.pip:
      name: "{{ item }}"
      executable: pip3.9
    loop:
    - boto3
    - botocore

  - name: create ec2 instances
    amazon.aws.ec2_instance:
      name: "{{ item }}"
      subnet_id: "{{ subnet_id }}"
      security_group: "{{ sg_id }}"
      image_id: "{{ ami_id }}"
      instance_type: "{{ instance_type }}"
    loop: "{{ instances }}"
    register: ec2_info

  - name: Debug EC2 Info (Check Structure)
    ansible.builtin.debug:
      var: ec2_info

  - name: Print EC2 Instance Information
    ansible.builtin.debug:
      msg: "Instance {{ item.instances[0].instance_id }} - Private IP: {{ item.instances[0].private_ip_address }}"
    loop: "{{ ec2_info.results }}"

  - name: create Route53 records  for private Ips
    amazon.aws.route53:
      state: present
      zone: "{{ zone }}"
      record: "{{ item.item }}.{{ zone }}"
      type: A
      ttl: 1
      value: "Instance {{ item.instances[0].instance_id }} - Private IP: {{ item.instances[0].private_ip_address }}"
      wait: true
      overwrite: true
    loop: "{{ ec2_info.results }}"
